
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates a YouTube search query related to a specific food storage query.
 *
 * - generateYoutubeSearchQuery - A function that generates a YouTube search query.
 * - GenerateYoutubeSearchQueryInput - The input type for the generateYoutubeSearchQuery function.
 * - GenerateYoutubeSearchQueryOutput - The return type for the generateYoutubeSearchQuery function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateYoutubeSearchQueryInputSchema = z.object({
  foodItem: z.string().describe('The specific food item the user is asking about.'),
  question: z.string().describe('The specific question the user has about the food item.'),
});
export type GenerateYoutubeSearchQueryInput = z.infer<typeof GenerateYoutubeSearchQueryInputSchema>;

const GenerateYoutubeSearchQueryOutputSchema = z.object({
  searchQuery: z
    .string()
    .describe('A YouTube search query string optimized to find relevant videos for the food item and question.'),
});
export type GenerateYoutubeSearchQueryOutput = z.infer<typeof GenerateYoutubeSearchQueryOutputSchema>;

export async function generateYoutubeSearchQuery(input: GenerateYoutubeSearchQueryInput): Promise<GenerateYoutubeSearchQueryOutput> {
  return generateYoutubeSearchQueryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'youtubeSearchQueryGenerationPrompt',
  input: {schema: GenerateYoutubeSearchQueryInputSchema},
  output: {schema: GenerateYoutubeSearchQueryOutputSchema},
  prompt: `You are an expert YouTube search curator specializing in food storage.
Given a food item and a question, your task is to generate **one single, effective YouTube search query string**.
This query string will be used directly by the user to search on YouTube for relevant videos.

**Do NOT provide URLs or full video titles.** Only provide the search query text itself.

User's Food Item: "{{{foodItem}}}"
User's Question: "{{{question}}}"

Example:
If Food Item is "avocado" and Question is "how to stop it from browning", a good search query is "how to keep avocado from browning".
If Food Item is "berries" and Question is "best way to wash and store", a good search query is "wash and store berries to last longer".

Generate the best possible YouTube search query based on the user's input.
`,
});

const generateYoutubeSearchQueryFlow = ai.defineFlow(
  {
    name: 'generateYoutubeSearchQueryFlow',
    inputSchema: GenerateYoutubeSearchQueryInputSchema,
    outputSchema: GenerateYoutubeSearchQueryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);

